<?xml version="1.0" encoding="utf-8"?><Database Name="Scheduled" Class="DatabaseQuerieDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Scheduled.mdf;Integrated Security=True" SettingsObjectName="SoftwareEngineeringProject.Properties.Settings" SettingsPropertyName="ScheduledConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Saved" Member="Saveds">
    <Type Name="Saved">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instructor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TestDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TestTime" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[CBT-PBT]" Member="CBT_PBT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Reporter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="admin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dateadded" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>